-- ==============================================================================
-- STUDIO VIRTUAL — SAFE MIGRATION & RLS SCRIPT
-- ==============================================================================

-- ─── 1. EXTENSIONS & SETUP ───────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── 2. SEGURO: GARANTIR COLUNA USER_ID EM TABELAS PRÉ-EXISTENTES ──────────────
DO $$ 
BEGIN
    -- artista
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artista') THEN
        IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'artista' AND column_name = 'user_id') THEN
            ALTER TABLE public.artista ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
        END IF;
    END IF;

    -- collections
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'collections') THEN
        IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'collections' AND column_name = 'user_id') THEN
            ALTER TABLE public.collections ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
        END IF;
    END IF;

    -- series
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'series') THEN
        IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'series' AND column_name = 'user_id') THEN
            ALTER TABLE public.series ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
        END IF;
    END IF;

    -- artworks
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artworks') THEN
        IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'artworks' AND column_name = 'user_id') THEN
            ALTER TABLE public.artworks ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
        END IF;
    END IF;
END $$;

-- ─── 3. CRIAR TABELAS CASO NÃO EXISTAM ───────────────────────────────────────

-- TABELA: artista
CREATE TABLE IF NOT EXISTS public.artista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT NOT NULL DEFAULT 'Nany Arruda',
    nomeartistico TEXT,
    email TEXT,
    nacionalidade TEXT,
    cidade TEXT,
    nascimento TEXT,
    website TEXT,
    telefone TEXT,
    whatsapp TEXT,
    bioshort TEXT,
    biolong TEXT,
    statement TEXT,
    tags TEXT,
    foto_url TEXT,
    selo_url TEXT,
    assinatura_url TEXT,
    fotos_profissionais JSONB DEFAULT '[]'::jsonb,
    instagrams JSONB DEFAULT '[]'::jsonb,
    social_links JSONB DEFAULT '[]'::jsonb,
    formacao JSONB DEFAULT '[]'::jsonb,
    premios JSONB DEFAULT '[]'::jsonb,
    residencias JSONB DEFAULT '[]'::jsonb,
    expos_individuais JSONB DEFAULT '[]'::jsonb,
    expos_coletivas JSONB DEFAULT '[]'::jsonb,
    publicacoes JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABELA: collections
CREATE TABLE IF NOT EXISTS public.collections (
    collection_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    collection_name TEXT NOT NULL,
    collection_description TEXT,
    start_date TEXT,
    end_date TEXT,
    total_items INT DEFAULT 0,
    item_types JSONB DEFAULT '[]'::jsonb,
    provenance_history JSONB DEFAULT '[]'::jsonb,
    acquisition_method TEXT,
    keywords JSONB DEFAULT '[]'::jsonb,
    thematic_descriptors JSONB DEFAULT '[]'::jsonb,
    artistic_theme TEXT,
    relevance_notes TEXT,
    physical_location TEXT,
    storage_reference TEXT,
    visibility_status TEXT DEFAULT 'private',
    cover_image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABELA: series
CREATE TABLE IF NOT EXISTS public.series (
    series_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    parent_collection_id UUID REFERENCES public.collections(collection_id) ON DELETE SET NULL,
    series_title TEXT NOT NULL,
    series_number INT,
    conceptual_statement TEXT,
    conceptual_summary TEXT,
    curatorial_narrative TEXT,
    thematic_connection TEXT,
    narrative_description TEXT,
    start_year INT,
    end_year INT,
    production_period TEXT,
    creation_locations TEXT,
    predominant_materials JSONB DEFAULT '[]'::jsonb,
    predominant_techniques JSONB DEFAULT '[]'::jsonb,
    edition_type TEXT,
    edition_fraction TEXT,
    print_run_total INT,
    display_order INT DEFAULT 0,
    group_label TEXT,
    keywords JSONB DEFAULT '[]'::jsonb,
    cover_image TEXT,
    cor TEXT DEFAULT '#000000',
    series_status TEXT DEFAULT 'Em andamento',
    visibility_status TEXT DEFAULT 'private',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABELA: artworks
CREATE TABLE IF NOT EXISTS public.artworks (
    artwork_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    accession_number TEXT,
    inventory_number TEXT,
    artwork_title TEXT NOT NULL,
    alternative_title TEXT,
    artwork_description TEXT,
    creation_date TEXT,
    creation_year INT,
    creation_city TEXT,
    creation_country TEXT,
    artist_name TEXT DEFAULT 'Nany Arruda',
    studio_name TEXT,
    attribution TEXT,
    medium TEXT,
    support TEXT,
    materials JSONB DEFAULT '[]'::jsonb,
    artistic_technique TEXT,
    interpretive_title TEXT,
    summary_sentence TEXT,
    curatorial_narrative TEXT,
    epigraph TEXT,
    intent_note JSONB,
    height NUMERIC,
    width NUMERIC,
    depth NUMERIC,
    weight NUMERIC,
    dimensions_unit TEXT DEFAULT 'cm',
    dimensions_formatted TEXT,
    dpi INT,
    resolution_px TEXT,
    condition_state TEXT DEFAULT 'excellent',
    conservation_notes TEXT,
    restoration_history JSONB DEFAULT '[]'::jsonb,
    certificate_of_authenticity BOOLEAN DEFAULT FALSE,
    certificate_url TEXT,
    signature_status TEXT,
    provenance_chain JSONB DEFAULT '[]'::jsonb,
    artwork_images JSONB DEFAULT '[]'::jsonb,
    artwork_images_labels JSONB DEFAULT '[]'::jsonb,
    detail_images JSONB DEFAULT '[]'::jsonb,
    process_images JSONB DEFAULT '[]'::jsonb,
    video_documentation JSONB DEFAULT '[]'::jsonb,
    cover_image TEXT,
    collection_reference UUID REFERENCES public.collections(collection_id) ON DELETE SET NULL,
    series_reference UUID REFERENCES public.series(series_id) ON DELETE SET NULL,
    classification TEXT DEFAULT 'singular',
    display_order INT DEFAULT 0,
    tags JSONB DEFAULT '[]'::jsonb,
    keywords JSONB DEFAULT '[]'::jsonb,
    exhibition_history JSONB DEFAULT '[]'::jsonb,
    publication_history JSONB DEFAULT '[]'::jsonb,
    exposed BOOLEAN DEFAULT FALSE,
    sale_status TEXT DEFAULT 'available',
    price NUMERIC,
    edition_number TEXT,
    copyright_holder TEXT DEFAULT 'Nany Arruda',
    visibility_status TEXT DEFAULT 'private',
    physical_location TEXT,
    sustainable_materials BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABELAS MANY-TO-MANY
CREATE TABLE IF NOT EXISTS public.artworks_series (
    artwork_id UUID REFERENCES public.artworks(artwork_id) ON DELETE CASCADE,
    series_id UUID REFERENCES public.series(series_id) ON DELETE CASCADE,
    PRIMARY KEY (artwork_id, series_id)
);

CREATE TABLE IF NOT EXISTS public.artworks_collections (
    artwork_id UUID REFERENCES public.artworks(artwork_id) ON DELETE CASCADE,
    collection_id UUID REFERENCES public.collections(collection_id) ON DELETE CASCADE,
    PRIMARY KEY (artwork_id, collection_id)
);

-- TABELA: portfolios
CREATE TABLE IF NOT EXISTS public.portfolios (
    portfolio_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    portfolio_title TEXT NOT NULL,
    artist_statement TEXT,
    template_type TEXT DEFAULT 'A',
    grid_columns INT DEFAULT 2,
    include_cover BOOLEAN DEFAULT TRUE,
    include_cv BOOLEAN DEFAULT TRUE,
    selected_artworks JSONB DEFAULT '[]'::jsonb,
    image_scales JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── 4. TRIGGERS AUTOMÁTICOS ─────────────────────────────────────────────────
DROP TRIGGER IF EXISTS set_updated_at_artista ON public.artista;
CREATE TRIGGER set_updated_at_artista BEFORE UPDATE ON public.artista FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_collections ON public.collections;
CREATE TRIGGER set_updated_at_collections BEFORE UPDATE ON public.collections FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_series ON public.series;
CREATE TRIGGER set_updated_at_series BEFORE UPDATE ON public.series FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_artworks ON public.artworks;
CREATE TRIGGER set_updated_at_artworks BEFORE UPDATE ON public.artworks FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_portfolios ON public.portfolios;
CREATE TRIGGER set_updated_at_portfolios BEFORE UPDATE ON public.portfolios FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- TABELA: certificate_templates
CREATE TABLE IF NOT EXISTS public.certificate_templates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    image_url TEXT NOT NULL,
    palette JSONB DEFAULT '[]'::jsonb NOT NULL,
    font_category TEXT DEFAULT 'sans-serif' NOT NULL,
    orientation TEXT DEFAULT 'landscape' NOT NULL,
    aspect_ratio NUMERIC(6,4) DEFAULT 1.4140 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABELA: usuarios_futuros (Lista de Espera)
CREATE TABLE IF NOT EXISTS public.usuarios_futuros (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    telefone TEXT,
    nome_artistico TEXT,
    cidade TEXT,
    pais TEXT DEFAULT 'Brasil',
    instagram TEXT,
    site TEXT,
    area_atuacao TEXT,
    mensagem TEXT,
    status TEXT DEFAULT 'pendente',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── 5. ROW LEVEL SECURITY (RLS) POLICIES ─────────────────────────────────────
ALTER TABLE public.artista ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artworks_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artworks_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificate_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own artist profile" ON public.artista;
CREATE POLICY "Users can manage own artist profile" ON public.artista FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own collections" ON public.collections;
CREATE POLICY "Users can manage own collections" ON public.collections FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own series" ON public.series;
CREATE POLICY "Users can manage own series" ON public.series FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own artworks" ON public.artworks;
CREATE POLICY "Users can manage own artworks" ON public.artworks FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own portfolios" ON public.portfolios;
CREATE POLICY "Users can manage own portfolios" ON public.portfolios FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own certificate templates" ON public.certificate_templates;
CREATE POLICY "Users can manage own certificate templates" ON public.certificate_templates FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ─── 6. STORAGE BUCKETS ──────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public) VALUES ('obras-images', 'obras-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('perfil', 'perfil', true) ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access to obras-images" ON storage.objects;
CREATE POLICY "Public Access to obras-images" ON storage.objects FOR SELECT USING (bucket_id = 'obras-images');

DROP POLICY IF EXISTS "Authenticated upload to obras-images" ON storage.objects;
CREATE POLICY "Authenticated upload to obras-images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'obras-images' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Public Access to perfil" ON storage.objects;
CREATE POLICY "Public Access to perfil" ON storage.objects FOR SELECT USING (bucket_id = 'perfil');

DROP POLICY IF EXISTS "Authenticated upload to perfil" ON storage.objects;
CREATE POLICY "Authenticated upload to perfil" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'perfil' AND auth.role() = 'authenticated');

